// Example: How to integrate the generated audio files into Linguini game

// 1. Load the language data (this would be generated by the Python script)
async function loadLanguageData() {
    const response = await fetch('language_data.json');
    const languages = await response.json();
    return languages;
}

// 2. Select a random language for today's puzzle
function selectDailyLanguage(languages) {
    // For daily challenge, use date as seed for consistent selection
    const today = new Date().toISOString().split('T')[0]; // "2025-10-30"
    const seed = today.split('-').join(''); // "20251030"
    const index = parseInt(seed) % languages.length;
    return languages[index];
}

// 3. Play the audio for the selected language
function playLanguageAudio(languageData) {
    // Randomly pick one of the available audio files for this language
    const audioFiles = languageData.audio_files;
    const randomAudio = audioFiles[Math.floor(Math.random() * audioFiles.length)];
    
    const audio = new Audio(`audio_files/${randomAudio.filename}`);
    audio.play();
    
    return randomAudio;
}

// 4. Complete game initialization
async function initializeGame() {
    // Load all language data
    const languages = await loadLanguageData();
    console.log(`Loaded ${languages.length} languages`);
    
    // Select today's language
    const todayLanguage = selectDailyLanguage(languages);
    console.log(`Today's language: ${todayLanguage.name}`);
    
    // Set up the game state
    const gameState = {
        correctLanguage: todayLanguage,
        correctLocation: todayLanguage.location,
        attempts: [],
        maxAttempts: 6,
        gameWon: false
    };
    
    // Set up play button
    document.getElementById('playBtn').addEventListener('click', () => {
        playLanguageAudio(todayLanguage);
    });
    
    return gameState;
}

// 5. Example language_data.json structure (generated by Python script)
/*
[
  {
    "name": "Spanish",
    "code": "es-ES",
    "location": [40.4168, -3.7038],
    "audio_files": [
      {
        "filename": "Spanish_male_phrase1.mp3",
        "phrase_number": 1,
        "gender": "male",
        "text": "Welcome to our beautiful country..."
      },
      {
        "filename": "Spanish_female_phrase1.mp3",
        "phrase_number": 1,
        "gender": "female",
        "text": "Welcome to our beautiful country..."
      },
      {
        "filename": "Spanish_male_phrase2.mp3",
        "phrase_number": 2,
        "gender": "male",
        "text": "The weather is lovely today..."
      },
      {
        "filename": "Spanish_female_phrase2.mp3",
        "phrase_number": 2,
        "gender": "female",
        "text": "The weather is lovely today..."
      }
    ]
  },
  {
    "name": "French",
    "code": "fr-FR",
    "location": [48.8566, 2.3522],
    "audio_files": [...]
  }
  // ... 48 more languages
]
*/

// 6. Enhanced game initialization with difficulty levels
async function initializeGameWithDifficulty(difficulty = 'easy') {
    const languages = await loadLanguageData();
    
    // Filter by difficulty
    let availableLanguages;
    switch(difficulty) {
        case 'easy':
            // Top 20 most spoken languages
            availableLanguages = languages.slice(0, 20);
            break;
        case 'medium':
            // Top 35 languages
            availableLanguages = languages.slice(0, 35);
            break;
        case 'hard':
            // All 50 languages
            availableLanguages = languages;
            break;
        default:
            availableLanguages = languages;
    }
    
    const todayLanguage = selectDailyLanguage(availableLanguages);
    
    return {
        correctLanguage: todayLanguage,
        correctLocation: todayLanguage.location,
        attempts: [],
        maxAttempts: 6,
        gameWon: false,
        difficulty: difficulty,
        availableLanguages: availableLanguages
    };
}

// 7. Audio preloading for better performance
async function preloadAudio(languageData) {
    const audioElements = [];
    
    for (const audioFile of languageData.audio_files) {
        const audio = new Audio(`audio_files/${audioFile.filename}`);
        // Preload the audio
        audio.preload = 'auto';
        audioElements.push({
            audio: audio,
            metadata: audioFile
        });
    }
    
    return audioElements;
}

// 8. Complete game setup with audio preloading
async function setupCompleteGame() {
    console.log('Initializing Linguini game...');
    
    try {
        // Load all language data
        const languages = await loadLanguageData();
        
        // Select today's language
        const todayLanguage = selectDailyLanguage(languages);
        
        // Preload today's audio files
        const preloadedAudio = await preloadAudio(todayLanguage);
        
        console.log(`✓ Game ready: ${todayLanguage.name}`);
        console.log(`✓ Preloaded ${preloadedAudio.length} audio files`);
        
        return {
            language: todayLanguage,
            audioFiles: preloadedAudio,
            currentAudioIndex: 0
        };
        
    } catch (error) {
        console.error('Error setting up game:', error);
        alert('Error loading game data. Please refresh the page.');
    }
}

// 9. Usage in your game
document.addEventListener('DOMContentLoaded', async () => {
    const gameData = await setupCompleteGame();
    
    // Play button handler
    document.getElementById('playBtn').addEventListener('click', () => {
        // Play the current audio file
        const currentAudio = gameData.audioFiles[gameData.currentAudioIndex];
        currentAudio.audio.play();
        
        // Rotate through available audio files on each play
        gameData.currentAudioIndex = 
            (gameData.currentAudioIndex + 1) % gameData.audioFiles.length;
    });
    
    // Rest of your game logic...
});

// 10. Statistics and tracking
function generateShareText(gameState) {
    const attempts = gameState.attempts.length;
    const maxAttempts = gameState.maxAttempts;
    const language = gameState.correctLanguage.name;
    
    const emoji = attempts <= 3 ? '🟩' : attempts <= 5 ? '🟨' : '🟥';
    
    return `Linguini 🌍
Language: ${language}
Found in ${attempts}/${maxAttempts} attempts
${emoji.repeat(attempts)}${'⬜'.repeat(maxAttempts - attempts)}

Play at: linguini.game`;
}

// Export for use in other modules
export {
    loadLanguageData,
    selectDailyLanguage,
    playLanguageAudio,
    initializeGame,
    initializeGameWithDifficulty,
    preloadAudio,
    setupCompleteGame,
    generateShareText
};
